Feature: Multi Language Support
The-Enthusiast-404/git-begin pull request #74
Opened 2024-09-02 22:20 UTC by rodriveiga01

# Summary

This pull request addresses issue #72 by implementing multi-language support across the website.

# Changes

- Language Dropdown: Introduced a dropdown menu that supports 9 languages: English, German, French, Spanish, Italian, Portuguese, Hindi, Simplified Chinese, and Traditional Chinese.
- Localization Files: Added a `locale` folder containing JSON files for each supported language.
- Translation Logic: Implemented translation logic using the i18n framework. All related functions are located in `locale/languageUtility.ts`.
- Text Insertion Format: Updated various files to comply with the new format for text insertion.
- Dynamic Categories: Refactored `data/categories.ts` into a function to facilitate translation. All necessary logic has been implemented.
- Responsive Footer: Modified the footer layout to transform into a flex-col structure on `mobile devices`, ensuring adequate space for the language dropdown.

All changes have been tested. The page reloads to update the text strings to the new language

# Contribution

This pull request resolves #72.

2024-09-02 22:25 UTC, rodriveiga01 commented
All translations were done in the website:https://translate.i18next.com

2024-09-02 22:28 UTC, rodriveiga01 commented
If needed to implement other languages, I can implement before merging

2024-09-03 02:30 UTC, dotslashbit commented
@rodriveiga01 Thank you so much for your contribution. It might take some time to review it as I don't have much time for the next 2 days. I hope you'll understand

2024-09-03 07:40 UTC, rodriveiga01 commented
Of course, take your time. Then let me know that you think

2024-09-03 13:14 UTC, omjogani requested changes
Left few comments, Overall great work! :rocket:

2024-09-03 13:14 UTC, omjogani commented on app/locale/languageUtility.ts
> +  }
What is the purpose of this? OR are We good to remove it?

2024-09-03 13:16 UTC, omjogani commented
We need to cross-check different language content too. We can't rely on a single tool. @rodriveiga01 @dotslashbit

2024-09-03 13:59 UTC, dotslashbit commented
@omjogani Can you suggest some other ways to cross check?

2024-09-03 14:22 UTC, rodriveiga01 commented on app/data/categories.ts
Thank you for the observation. Already updated with new commit

2024-09-03 14:47 UTC, rodriveiga01 commented
@omjogani I agree on cross checking but do you mean like testing various translators or other thing?

2024-09-03 15:44 UTC, omjogani commented
> @omjogani I agree on cross checking but do you mean like testing various translators or other thing?

Either we get tested by local people, who know that language very well OR another option could be Comparing translation with different tools.

2024-09-03 15:54 UTC, omjogani commented on app/hooks/useCategories.ts
instead of writing code logic with `for each` loop, I would suggest to use the map and predefined function, that helps in code readability.

Here is how should you proceed:
```jsx
import { categories } from "~/data/categories";
import { useTranslatedText } from "~/locale/languageUtility";

export function useCategories() {
    const rawCategories = categories;
    const t = useTranslatedText();

    const translatedCategories = rawCategories.map(category => ({
        ...category,
        label: t(category.label)
    }));

    return translatedCategories;
}
```

2024-09-03 15:58 UTC, omjogani commented on app/locale/languageUtility.ts
> +}
This can be still improved with a guard clause and `await`, something like...

```js
async function updateLanguage() {
  const currentLanguage = getCurrentLanguage();

  if (!currentLanguage || currentLanguage === i18n.language) {
    return;
  }

  try {
    await i18n.changeLanguage(currentLanguage);
    // Language was changed successfully
  } catch (error) {
    console.error(`Error changing language to ${currentLanguage}:`, error);
  }
}
``` 

instead of empty block we should use `await` and guard clause (early return) helps in improving code readability

2024-09-03 16:12 UTC, omjogani commented on app/locale/languageUtility.ts
> +}
That's the beauty of Open Source!

2024-09-03 16:15 UTC, omjogani approved these changes
Looks good to me! Thanks @rodriveiga01 for the contribution, You're following good naming convention, that's good part!

2024-09-03 16:16 UTC, rodriveiga01 commented
I use camelCase in variables and functions and PascalCase on class and other important things

2024-09-03 16:21 UTC, rodriveiga01 commented
@dotslashbit I think it can go for production now

2024-09-03 16:23 UTC, omjogani commented
> I use camelCase in variables and functions and PascalCase on class and other important things

That's convention, I mean to say meaningful naming.

2024-09-03 16:23 UTC, omjogani commented
> @dotslashbit I think it can go for production now

We are good to merge @dotslashbit :green_circle:

2024-09-03 16:27 UTC, dotslashbit commented
@rodriveiga01 Thank you so much for your contribution, it really means a lot and @omjogani I really appreciate your efforts into reviewing all these PRs, your experience is really helping this project.

Thank you both of you for being a part of this project. I can't be more lucky than this 😊

2024-09-03 16:27 UTC, merged

2024-09-03 16:29 UTC, rodriveiga01 commented
I just want to help and this seems a great project to begin to contribute in open source. Let's continue to improve